// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug: Log environment variables (only in development)
if (import.meta.env.DEV) {
  console.log('🔍 Debug - Variables d\'environnement:');
  console.log('  VITE_SUPABASE_URL:', SUPABASE_URL ? `${SUPABASE_URL.substring(0, 30)}...` : '❌ UNDEFINED');
  console.log('  VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 30)}...` : '❌ UNDEFINED');
}

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Variables d\'environnement Supabase manquantes !');
  console.error('Vérifiez que votre fichier .env contient :');
  console.error('VITE_SUPABASE_URL=https://hxihjvqvmujobqkfcdll.supabase.co');
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY=votre-clé-publique');
  console.error('\nCes valeurs se trouvent dans : Supabase Dashboard → Settings → API');
  console.error('\n💡 IMPORTANT: Redémarrez le serveur après avoir modifié le fichier .env !');
  console.error('   Arrêtez le serveur (Ctrl+C) puis relancez: npm run dev');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Expose supabase globally for debugging (only in development)
if (import.meta.env.DEV && typeof window !== 'undefined') {
  (window as any).supabase = supabase;
}